bag/urls.py
from django.conf.urls import url
from . import views

app_name = 'bag'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

personalise/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('personalise/<product_id>', views.personalise, name='personalise'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<product_id>', views.product_detail, name='product_detail'),
]

word4u/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('personalise/', include('personalise.urls')),
    path('bag/', include('bag.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag/models.py
from django.db import models

# Create your models here.

checkout/models.py
from django.db import models
from products.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    contact_number = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

home/models.py
from django.db import models

# Create your models here.

personalise/models.py
from django.db import models


class Personalise(models.Model):
    product_number = models.CharField(max_length=32, null=False, editable=False)
    background_choices = (
        ('standard', 'standard as sample'),
        ('simplify', 'less elements'),
        ('elaborate', 'more elements'),
    )
    text_color_choices = (
        ('standard', 'standard as sample'),
        ('golden', 'golden tone'),
        ('silver', 'silverish tone'),
    )
    background = models.CharField(max_length=10, choices=background_choices, default='standard',)
    text_color = models.CharField(max_length=10, choices=text_color_choices, default='standard',)
    text_content = models.TextField(max_length=20)
    extra_requirements = models.TextField(max_length=255)

    def __str__(self):
        return self.product_number

products/models.py
from django.db import models


class Product(models.Model):
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

bag/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

personalise/forms.py
from django.db import models
from django import forms


from .models import Product


class PersonalisationForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'background',
            'text_color',
            'text_content',
            'extra_requirements',
        ]

bag/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('bag:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('bag:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'bag/bag.html', {'cart': cart})

checkout/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

personalise/views.py
from django.shortcuts import render, get_object_or_404
from products.models import Product


def personalise(request, product_id):

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'personalise.html', context)

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from bag.forms import CartAddProductForm


def all_products(request):

    products = Product.objects.all()

    context = {
        'products': products,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):

    product = get_object_or_404(Product, pk=product_id)
    cart_product_form = CartAddProductForm()

    context = {
        'product': product,
        'cart_product_form':cart_product_form,
    }

    return render(request, 'products/product_detail.html', context)

bag/templates/bag/bag.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 20%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "bag:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead >
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "bag:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "bag:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>kshs. {{ item.price }}</td>
                            <td>kshs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr >
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "products" %}" class="btn btn-default">Continue Shopping</a>
        </p>
        </div>
    </div>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>

{% endblock %}

{% block content %}

 <main role="main">
<!-- Banner -->
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Welcome</h1>
          <p class="lead text-muted">Choose your favourite design, and we will personalise it for your need! </p>
          <p>
            <a href="#" class="btn btn-primary my-2">New here?</a>
            <a href="#" class="btn btn-secondary my-2">Browse</a>
          </p>
        </div>
      </section>

      <!-- Why choose us -->
      <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" data-src="media/reasonone.jpg" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">
                            <strong>Various designs for your choice</strong> 
                        </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" data-src="media/reasontwo.jpg" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">
                            <strong>Personalisation to suit your needs</strong> 
                        </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" data-src="media/reasonthree.jpg" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">
                            <strong>A team of passionate designers</strong> 
                        </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
      </div>

<!-- Testmonies -->

<div class="container container-fluid">
<div class="card-deck">
  <div class="card">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
</div>


</div>
{% endblock %}

personalise/templates/includes/personalisation_form_script.html
<script type="text/javascript">



</script>

personalise/templates/personalise.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>

{% endblock %}

{% block content %}

<div class="container mb-2">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="logo-font mb-4">Personalisation details</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
            </div>
        </div>

        <div class="row">
            <form>
  <div class="form-group">
    <label for="select-bg">Background</label>
    <select class="form-control" id="select-bg">
      <option>standard as sample</option>
      <option>less elements</option>
      <option>more elements</option>
    </select>
  </div>
  <div class="form-group">
    <label for="select-text-color">Text Color</label>
    <select class="form-control" id="select-text-color">
      <option>standard as sample</option>
      <option>golden tone</option>
      <option>silver tone</option>
    </select>
  </div>
  <div class="form-group">
   <label for="text-content">Text Content</label>
   <input type="text" id="text-content" class="form-control" aria-describedby="textHelpBlock">
   <small id="textHelpBlock" class="form-text text-muted">
  Your text must be limited within 20 words or less for capatability.
</small>
  </div>
  <div class="form-group">
    <label for="more-details">Extra requirements</label>
    <textarea class="form-control" id="more-details" rows="3"></textarea>
  </div>
</form>
        </div>
</div>


{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<div class="container-fluid">
        <div class="row">
        <div class="col text-center mt-3">
           <h2 class="logo-font">Design details</h2>
           <hr class="w-50 mb-1">
        </div>
    </div>
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <h3 class="mb-0">{{ product.name }}</h3>
                    <hr>
                    <p class="lead mb-0 text-left font-weight-bold">Price(per page): £{{ product.price }}</p>
                    <hr>
                    <p class="mt-3">{{ product.description }}</p>
                    <hr>
                    <a href="{% url 'personalise' product.id %}" class="btn btn-light rounded-0 mt-5">Make Your Design</a>
                    <form action="{% url "bag:cart_add" product.id %}" method="post">
                        {% csrf_token %}
                        {{ cart_product_form }}
                        <input type="submit" value="add to cart" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
<!-- Banner -->
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
           <h2 class="logo-font">Products</h2>
           <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row">
        <div class="product-container col-10 offset-1">
            <div class="row mt-1 mb-2"></div>
                <div class="row">
        {% for product in products %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100 border-0">
                                
                                <a href="{% url 'product_detail' product.id %}">
                                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                </a>
                                
                                <div class="card-body pb-0">
                                    <p class="mb-0">{{ product.name }}</p>
                                </div>
                                <div class="card-footer bg-white pt-0 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                                <hr>
                            </div>
                        {% endif %}                        
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                <hr>
                            </div>
                        {% endif %}

                    {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    
    {% block meta %}
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}

    {% block extra_meta %}
    {% endblock %}

    {% block corecss %}
    <link rel="apple-touch-icon" sizes="180x180" href="media/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="media/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="media/favicon/favicon-16x16.png">
    <link rel="manifest" href="media/favicon/site.webmanifest">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}

    {% block extra_css %}
    {% endblock %}

    {% block corejs %}
    <script src="https://kit.fontawesome.com/e9c73d7092.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% endblock %}

    {% block extra_js %}
    {% endblock %}

    <title>WORD4U 
    {% block extra_title %}
    {% endblock %}</title>
  </head>

<body>

  <header class="container-fluid fixed-top">
        <div id="topnav" class="row bg-white pt-lg-2 d-none d-lg-flex">
            <div class="col-12 col-lg-8 my-auto py-1 py-lg-0">
                <a href="{% url 'home' %}" class="nav-link main-logo-link">
                    <h1 class="logo-font text-black my-0">WORD4U</h1>
                </a>
            </div>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                <ul class="list-inline list-unstyled text-center text-lg-right my-0">
                    <li class="list-inline-item dropdown">
                        <a class="text-black nav-link" href="#" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="text-center">
                                <div><i class="fas fa-user fa-lg"></i></div>
                                <p class="my-0">My Account</p>
                            </div>
                        </a>
                        <div class="dropdown-menu border-0" aria-labelledby="user-options">
                            {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser %}
                                    <a href="" class="dropdown-item">Product Management</a>
                                {% endif %}
                                <a href="" class="dropdown-item">My Profile</a>
                                <a href="" class="dropdown-item">Logout</a>
                            {% else %}
                                <a href="" class="dropdown-item">Register</a>
                                <a href="" class="dropdown-item">Login</a>
                            {% endif %}
                        </div>
                    </li>
                    <li class="list-inline-item">
                        <a class="{% if grand_total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link" href="{% url 'bag:cart_detail' %}">
                            <div class="text-center">
                                <div><i class="fas fa-shopping-bag fa-lg"></i></div>
                                <p class="my-0">
                                    {% if grand_total %}
                                        ${{ grand_total|floatformat:2 }}
                                    {% else %}
                                        £ 0.00
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row bg-white">
            <nav class="navbar navbar-expand-lg navbar-light w-100">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% include 'includes/mobile-top-header.html' %}
                {% include 'includes/main-nav.html' %}
            </nav>
        </div>
        <div id="delivery-banner" class="row text-center">
            <div class="col bg-black text-white">
                <h4 class="logo-font my-1">20% Discount on orders over £{{ bundle_discount_threshold }}!</h4>                
            </div>            
        </div>
    </header>

{% if messages %}
<div class="message-container">
</div>
{% endif %}

{% block page_header %}
{% endblock %}

{% block content %}
{% endblock %}

{% block postloadjs %}
{% endblock %}

  </body>
</html>

templates/includes/main-nav.html
<div class="collapse navbar-collapse" id="main-nav">
    <ul class="navbar-nav w-auto mx-auto">
        <li class="nav-item">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="{% url 'home' %}" id="home-link">
                Home
            </a>
        </li>
        <li class="nav-item">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="{% url 'products' %}" id="all-products-link">
                designs
            </a>
        </li>

        <li class="nav-item">
            <a class="logo-font font-weight-bold nav-link text-black" href="#" id="specials-link">
                Freebies
            </a>
        </li>
    </ul>
</div>

templates/includes/mobile-top-header.html
<li class="list-inline-item dropdown">
    <a class="text-black nav-link d-block d-lg-none" href="#" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-user fa-lg"></i></div>
            <p class="my-0">My Account</p>
        </div>
    </a>
    <div class="dropdown-menu border-0" aria-labelledby="user-options">
        {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <a href="" class="dropdown-item">Product Management</a>
            {% endif %}
            <a href="" class="dropdown-item">My Profile</a>
            <a href="" class="dropdown-item">Logout</a>
        {% else %}
            <a href="" class="dropdown-item">Register</a>
            <a href="" class="dropdown-item">Login</a>
        {% endif %}
    </div>
</li>
<li class="list-inline-item">
    <a class="{% if grand_total %}text-primary font-weight-bold{% else %}text-black{% endif %} nav-link d-block d-lg-none" href="{% url 'bag:cart_detail' %}">
        <div class="text-center">
            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
            <p class="my-0">
                {% if grand_total %}
                    ${{ grand_total|floatformat:2 }}
                {% else %}
                    £0.00
                {% endif %}
            </p>
        </div>
    </a>
</li>